version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # UI
      - "6831:6831/udp" # Jaeger compact
      - "6832:6832/udp" # Jaeger binary
      - "14250:14250" # Jaeger gRPC
    networks:
      - tracing-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - jaeger
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - tracing-network
  api1:
    build:
      context: . # Путь к директории с API 1
      dockerfile: app1/Dockerfile
    container_name: api1
    ports:
      - "5001:5001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - jaeger
      - otel-collector
    networks:
      - tracing-network
  api2:
    build:
      context: . # Путь к директории с API 2
      dockerfile: app2/Dockerfile
    container_name: api2
    ports:
      - "5002:5002"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - jaeger
      - otel-collector
    networks:
      - tracing-network

networks:
  tracing-network:
    driver: bridge
